import { isRecord } from "@bitwobbly/shared";

import { escapeHtml } from "./html-utils.ts";

export const DEFAULT_EMAIL_FROM =
  "BitWobbly <bitwobbly@notifications.nicholasgriffin.co.uk>";

export interface SendMonitorAlertEmailParams {
  email: string;
  statusText: string;
  alertId: string;
  monitorId: string;
  status: "up" | "down";
  reason?: string;
  incidentId?: string;
  from?: string;
  subjectPrefix?: string;
  resendApiKey: string;
}

export interface SendIssueAlertEmailParams {
  email: string;
  alertId: string;
  ruleName: string;
  severity: "critical" | "warning" | "resolved";
  triggerType: string;
  triggerValue?: number;
  threshold?: number;
  issue: {
    id: string;
    title: string;
    level: string;
    culprit?: string | null;
    eventCount: number;
    userCount: number;
    firstSeenAt: number;
    lastSeenAt: number;
  };
  projectName: string;
  environment?: string;
  from?: string;
  subjectPrefix?: string;
  resendApiKey: string;
}

export interface EmailDeliveryResult {
  subject: string;
  providerMessageId: string | null;
}

export async function sendIssueAlertEmail({
  email,
  alertId,
  ruleName,
  severity,
  triggerType,
  triggerValue,
  threshold,
  issue,
  projectName,
  environment,
  from,
  subjectPrefix,
  resendApiKey,
}: SendIssueAlertEmailParams): Promise<EmailDeliveryResult> {
  const severityColors = {
    critical: "#dc3545",
    warning: "#ffc107",
    resolved: "#28a745",
  };

  const severityEmojis = {
    critical: "🔴",
    warning: "🟡",
    resolved: "🟢",
  };

  const triggerDescription = getTriggerDescription(
    triggerType,
    triggerValue,
    threshold
  );
  const firstSeen = new Date(issue.firstSeenAt * 1000).toLocaleString();
  const lastSeen = new Date(issue.lastSeenAt * 1000).toLocaleString();
  const safeRuleName = escapeHtml(ruleName);
  const safeIssueTitle = escapeHtml(issue.title);
  const safeCulprit = issue.culprit ? escapeHtml(issue.culprit) : null;
  const safeTriggerDescription = escapeHtml(triggerDescription);
  const safeLevel = escapeHtml(issue.level);
  const safeProjectName = escapeHtml(projectName);
  const safeEnvironment = environment ? escapeHtml(environment) : null;
  const safeAlertId = escapeHtml(alertId);
  const subject = buildIssueSubject({
    subjectPrefix,
    emoji: severityEmojis[severity],
    projectName,
    title: issue.title,
  });

  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${resendApiKey}`,
    },
    body: JSON.stringify({
      from: normaliseFromAddress(from),
      to: [email],
      subject,
      html: `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>BitWobbly Issue Alert</title>
          </head>
          <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="background: ${severityColors[severity]}; padding: 20px; border-radius: 8px; margin-bottom: 20px; color: white;">
              <h1 style="margin: 0;">${severityEmojis[severity]} ${severity.toUpperCase()}</h1>
              <p style="margin: 10px 0 0 0; font-size: 14px; opacity: 0.9;">Rule: ${safeRuleName}</p>
            </div>

            <div style="background: white; padding: 20px; border-radius: 8px; border: 1px solid #dee2e6; margin-bottom: 20px;">
              <h2 style="margin-top: 0; color: #495057;">${safeIssueTitle}</h2>
              ${safeCulprit ? `<p style="color: #6c757d; margin: 5px 0;">${safeCulprit}</p>` : ""}
              <p><strong>Trigger:</strong> ${safeTriggerDescription}</p>
              <p><strong>Level:</strong> ${safeLevel}</p>
              <p><strong>Project:</strong> ${safeProjectName}${safeEnvironment ? ` (${safeEnvironment})` : ""}</p>
            </div>

            <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
              <h3 style="margin-top: 0; color: #495057;">Issue Statistics</h3>
              <p><strong>Events:</strong> ${issue.eventCount.toLocaleString()}</p>
              <p><strong>Users affected:</strong> ${issue.userCount.toLocaleString()}</p>
              <p><strong>First seen:</strong> ${firstSeen}</p>
              <p><strong>Last seen:</strong> ${lastSeen}</p>
              <p style="font-size: 12px; color: #6c757d;">Alert ID: ${safeAlertId}</p>
            </div>

            <div style="margin-top: 20px; padding: 20px; background: #e9ecef; border-radius: 8px;">
              <p style="margin: 0; font-size: 14px; color: #495057;">
                This alert was generated by <a href="https://bitwobbly.com" style="color: #007bff;">BitWobbly</a> error tracking.
              </p>
            </div>
          </body>
        </html>
      `,
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to send email: ${error}`);
  }

  return {
    subject,
    providerMessageId: await getProviderMessageId(response),
  };
}

function getTriggerDescription(
  triggerType: string,
  triggerValue?: number,
  threshold?: number
): string {
  switch (triggerType) {
    case "new_issue":
      return "New issue detected";
    case "issue_regression":
      return "Previously resolved issue has regressed";
    case "event_threshold":
      return triggerValue !== undefined && threshold !== undefined
        ? `Event count (${triggerValue}) exceeded threshold (${threshold})`
        : "Event threshold exceeded";
    case "user_threshold":
      return triggerValue !== undefined && threshold !== undefined
        ? `Unique users (${triggerValue}) exceeded threshold (${threshold})`
        : "User threshold exceeded";
    case "status_change":
      return "Issue status changed";
    case "high_priority":
      return "High priority error detected";
    default:
      return "Alert triggered";
  }
}

export async function sendAlertEmail({
  email,
  statusText,
  alertId,
  monitorId,
  status,
  reason,
  incidentId,
  from,
  subjectPrefix,
  resendApiKey,
}: SendMonitorAlertEmailParams): Promise<EmailDeliveryResult> {
  const safeStatusText = escapeHtml(statusText);
  const safeAlertId = escapeHtml(alertId);
  const safeMonitorId = escapeHtml(monitorId);
  const safeReason = reason ? escapeHtml(reason) : null;
  const safeIncidentId = incidentId ? escapeHtml(incidentId) : null;
  const subject = `${subjectPrefix?.trim() || "BitWobbly Alert"} - ${statusText}`;

  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${resendApiKey}`,
    },
    body: JSON.stringify({
      from: normaliseFromAddress(from),
      to: [email],
      subject,
      html: `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>BitWobbly Alert</title>
          </head>
          <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
              <h1 style="margin: 0; color: #495057;">${safeStatusText}</h1>
              <p style="margin: 10px 0 0 0; font-size: 14px; color: #6c757d;">Alert ID: ${safeAlertId}</p>
            </div>
            
            <div style="background: white; padding: 20px; border-radius: 8px; border: 1px solid #dee2e6;">
              <h2 style="margin-top: 0; color: #495057;">Service Details</h2>
              <p><strong>Monitor ID:</strong> ${safeMonitorId}</p>
              <p><strong>Status:</strong> ${status.toUpperCase()}</p>
              ${safeReason ? `<p><strong>Reason:</strong> ${safeReason}</p>` : ""}
              ${safeIncidentId ? `<p><strong>Incident ID:</strong> ${safeIncidentId}</p>` : ""}
              <p><strong>Time:</strong> ${new Date().toLocaleString()}</p>
            </div>
            
            <div style="margin-top: 20px; padding: 20px; background: #e9ecef; border-radius: 8px;">
              <p style="margin: 0; font-size: 14px; color: #495057;">
                This alert was generated by <a href="https://bitwobbly.com" style="color: #007bff;">BitWobbly</a> monitoring system.
              </p>
            </div>
          </body>
        </html>
      `,
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to send email: ${error}`);
  }

  return {
    subject,
    providerMessageId: await getProviderMessageId(response),
  };
}

async function getProviderMessageId(response: Response): Promise<string | null> {
  const contentType = response.headers.get("content-type") || "";
  if (!contentType.includes("application/json")) return null;

  const body: unknown = await response.json().catch(() => null);
  if (!isRecord(body)) return null;
  return typeof body.id === "string" ? body.id : null;
}

function normaliseFromAddress(from?: string): string {
  const trimmed = from?.trim();
  if (!trimmed) return DEFAULT_EMAIL_FROM;
  if (trimmed.includes("<")) return trimmed;
  return `BitWobbly <${trimmed}>`;
}

function buildIssueSubject(input: {
  subjectPrefix?: string;
  emoji: string;
  projectName: string;
  title: string;
}): string {
  const alertSubject = `${input.emoji} [${input.projectName}] ${input.title}`;
  const prefix = input.subjectPrefix?.trim();
  return prefix ? `${prefix} - ${alertSubject}` : alertSubject;
}
