export interface SendMonitorAlertEmailParams {
  email: string;
  statusText: string;
  alertId: string;
  monitorId: string;
  status: "up" | "down";
  reason?: string;
  incidentId?: string;
  resendApiKey: string;
}

export interface SendIssueAlertEmailParams {
  email: string;
  alertId: string;
  ruleName: string;
  severity: "critical" | "warning" | "resolved";
  triggerType: string;
  triggerValue?: number;
  threshold?: number;
  issue: {
    id: string;
    title: string;
    level: string;
    culprit?: string | null;
    eventCount: number;
    userCount: number;
    firstSeenAt: number;
    lastSeenAt: number;
  };
  projectName: string;
  environment?: string;
  resendApiKey: string;
}

export async function sendIssueAlertEmail({
  email,
  alertId,
  ruleName,
  severity,
  triggerType,
  triggerValue,
  threshold,
  issue,
  projectName,
  environment,
  resendApiKey,
}: SendIssueAlertEmailParams): Promise<void> {
  const severityColors = {
    critical: "#dc3545",
    warning: "#ffc107",
    resolved: "#28a745",
  };

  const severityEmojis = {
    critical: "🔴",
    warning: "🟡",
    resolved: "🟢",
  };

  const triggerDescription = getTriggerDescription(
    triggerType,
    triggerValue,
    threshold,
  );
  const firstSeen = new Date(issue.firstSeenAt * 1000).toLocaleString();
  const lastSeen = new Date(issue.lastSeenAt * 1000).toLocaleString();

  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${resendApiKey}`,
    },
    body: JSON.stringify({
      from: "BitWobbly <bitwobbly@notifications.nicholasgriffin.dev>",
      to: [email],
      subject: `${severityEmojis[severity]} [${projectName}] ${issue.title}`,
      html: `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>BitWobbly Issue Alert</title>
          </head>
          <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="background: ${severityColors[severity]}; padding: 20px; border-radius: 8px; margin-bottom: 20px; color: white;">
              <h1 style="margin: 0;">${severityEmojis[severity]} ${severity.toUpperCase()}</h1>
              <p style="margin: 10px 0 0 0; font-size: 14px; opacity: 0.9;">Rule: ${ruleName}</p>
            </div>

            <div style="background: white; padding: 20px; border-radius: 8px; border: 1px solid #dee2e6; margin-bottom: 20px;">
              <h2 style="margin-top: 0; color: #495057;">${issue.title}</h2>
              ${issue.culprit ? `<p style="color: #6c757d; margin: 5px 0;">${issue.culprit}</p>` : ""}
              <p><strong>Trigger:</strong> ${triggerDescription}</p>
              <p><strong>Level:</strong> ${issue.level}</p>
              <p><strong>Project:</strong> ${projectName}${environment ? ` (${environment})` : ""}</p>
            </div>

            <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
              <h3 style="margin-top: 0; color: #495057;">Issue Statistics</h3>
              <p><strong>Events:</strong> ${issue.eventCount.toLocaleString()}</p>
              <p><strong>Users affected:</strong> ${issue.userCount.toLocaleString()}</p>
              <p><strong>First seen:</strong> ${firstSeen}</p>
              <p><strong>Last seen:</strong> ${lastSeen}</p>
              <p style="font-size: 12px; color: #6c757d;">Alert ID: ${alertId}</p>
            </div>

            <div style="margin-top: 20px; padding: 20px; background: #e9ecef; border-radius: 8px;">
              <p style="margin: 0; font-size: 14px; color: #495057;">
                This alert was generated by <a href="https://bitwobbly.com" style="color: #007bff;">BitWobbly</a> error tracking.
              </p>
            </div>
          </body>
        </html>
      `,
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to send email: ${error}`);
  }
}

function getTriggerDescription(
  triggerType: string,
  triggerValue?: number,
  threshold?: number,
): string {
  switch (triggerType) {
    case "new_issue":
      return "New issue detected";
    case "issue_regression":
      return "Previously resolved issue has regressed";
    case "event_threshold":
      return triggerValue !== undefined && threshold !== undefined
        ? `Event count (${triggerValue}) exceeded threshold (${threshold})`
        : "Event threshold exceeded";
    case "user_threshold":
      return triggerValue !== undefined && threshold !== undefined
        ? `Unique users (${triggerValue}) exceeded threshold (${threshold})`
        : "User threshold exceeded";
    case "status_change":
      return "Issue status changed";
    case "high_priority":
      return "High priority error detected";
    default:
      return "Alert triggered";
  }
}

export async function sendAlertEmail({
  email,
  statusText,
  alertId,
  monitorId,
  status,
  reason,
  incidentId,
  resendApiKey,
}: SendMonitorAlertEmailParams): Promise<void> {
  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${resendApiKey}`,
    },
    body: JSON.stringify({
      from: "BitWobbly <bitwobbly@notifications.nicholasgriffin.dev>",
      to: [email],
      subject: `BitWobbly Alert - ${statusText}`,
      html: `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>BitWobbly Alert</title>
          </head>
          <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
              <h1 style="margin: 0; color: #495057;">${statusText}</h1>
              <p style="margin: 10px 0 0 0; font-size: 14px; color: #6c757d;">Alert ID: ${alertId}</p>
            </div>
            
            <div style="background: white; padding: 20px; border-radius: 8px; border: 1px solid #dee2e6;">
              <h2 style="margin-top: 0; color: #495057;">Service Details</h2>
              <p><strong>Monitor ID:</strong> ${monitorId}</p>
              <p><strong>Status:</strong> ${status.toUpperCase()}</p>
              ${reason ? `<p><strong>Reason:</strong> ${reason}</p>` : ""}
              ${incidentId ? `<p><strong>Incident ID:</strong> ${incidentId}</p>` : ""}
              <p><strong>Time:</strong> ${new Date().toLocaleString()}</p>
            </div>
            
            <div style="margin-top: 20px; padding: 20px; background: #e9ecef; border-radius: 8px;">
              <p style="margin: 0; font-size: 14px; color: #495057;">
                This alert was generated by <a href="https://bitwobbly.com" style="color: #007bff;">BitWobbly</a> monitoring system.
              </p>
            </div>
          </body>
        </html>
      `,
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to send email: ${error}`);
  }
}
