export interface SendMonitorAlertEmailParams {
  email: string;
  statusText: string;
  alertId: string;
  monitorId: string;
  status: 'up' | 'down';
  reason?: string;
  incidentId?: string;
  resendApiKey: string;
}

export async function sendAlertEmail({
  email,
  statusText,
  alertId,
  monitorId,
  status,
  reason,
  incidentId,
  resendApiKey,
}: SendMonitorAlertEmailParams): Promise<void> {
  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${resendApiKey}`,
    },
    body: JSON.stringify({
      from: 'BitWobbly <bitwobbly@notifications.nicholasgriffin.dev>',
      to: [email],
      subject: `BitWobbly Alert - ${statusText}`,
      html: `
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>BitWobbly Alert</title>
          </head>
          <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
              <h1 style="margin: 0; color: #495057;">${statusText}</h1>
              <p style="margin: 10px 0 0 0; font-size: 14px; color: #6c757d;">Alert ID: ${alertId}</p>
            </div>
            
            <div style="background: white; padding: 20px; border-radius: 8px; border: 1px solid #dee2e6;">
              <h2 style="margin-top: 0; color: #495057;">Service Details</h2>
              <p><strong>Monitor ID:</strong> ${monitorId}</p>
              <p><strong>Status:</strong> ${status.toUpperCase()}</p>
              ${reason ? `<p><strong>Reason:</strong> ${reason}</p>` : ''}
              ${incidentId ? `<p><strong>Incident ID:</strong> ${incidentId}</p>` : ''}
              <p><strong>Time:</strong> ${new Date().toLocaleString()}</p>
            </div>
            
            <div style="margin-top: 20px; padding: 20px; background: #e9ecef; border-radius: 8px;">
              <p style="margin: 0; font-size: 14px; color: #495057;">
                This alert was generated by <a href="https://bitwobbly.com" style="color: #007bff;">BitWobbly</a> monitoring system.
              </p>
            </div>
          </body>
        </html>
      `,
    }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to send email: ${error}`);
  }
}
