/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as StatusSlugRouteImport } from './routes/status/$slug'
import { Route as AppStatusPagesRouteImport } from './routes/app/status-pages'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppMonitorsRouteImport } from './routes/app/monitors'
import { Route as AppIncidentsRouteImport } from './routes/app/incidents'
import { Route as AppComponentsRouteImport } from './routes/app/components'
import { Route as ApiWebhooksMonitorIdRouteImport } from './routes/api.webhooks.$monitorId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const StatusSlugRoute = StatusSlugRouteImport.update({
  id: '/status/$slug',
  path: '/status/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStatusPagesRoute = AppStatusPagesRouteImport.update({
  id: '/status-pages',
  path: '/status-pages',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitorsRoute = AppMonitorsRouteImport.update({
  id: '/monitors',
  path: '/monitors',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppComponentsRoute = AppComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhooksMonitorIdRoute = ApiWebhooksMonitorIdRouteImport.update({
  id: '/api/webhooks/$monitorId',
  path: '/api/webhooks/$monitorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/components': typeof AppComponentsRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/monitors': typeof AppMonitorsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/status-pages': typeof AppStatusPagesRoute
  '/status/$slug': typeof StatusSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/webhooks/$monitorId': typeof ApiWebhooksMonitorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/components': typeof AppComponentsRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/monitors': typeof AppMonitorsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/status-pages': typeof AppStatusPagesRoute
  '/status/$slug': typeof StatusSlugRoute
  '/app': typeof AppIndexRoute
  '/api/webhooks/$monitorId': typeof ApiWebhooksMonitorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/components': typeof AppComponentsRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/monitors': typeof AppMonitorsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/status-pages': typeof AppStatusPagesRoute
  '/status/$slug': typeof StatusSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/webhooks/$monitorId': typeof ApiWebhooksMonitorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/components'
    | '/app/incidents'
    | '/app/monitors'
    | '/app/notifications'
    | '/app/settings'
    | '/app/status-pages'
    | '/status/$slug'
    | '/app/'
    | '/api/webhooks/$monitorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/app/components'
    | '/app/incidents'
    | '/app/monitors'
    | '/app/notifications'
    | '/app/settings'
    | '/app/status-pages'
    | '/status/$slug'
    | '/app'
    | '/api/webhooks/$monitorId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/components'
    | '/app/incidents'
    | '/app/monitors'
    | '/app/notifications'
    | '/app/settings'
    | '/app/status-pages'
    | '/status/$slug'
    | '/app/'
    | '/api/webhooks/$monitorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  StatusSlugRoute: typeof StatusSlugRoute
  ApiWebhooksMonitorIdRoute: typeof ApiWebhooksMonitorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/status/$slug': {
      id: '/status/$slug'
      path: '/status/$slug'
      fullPath: '/status/$slug'
      preLoaderRoute: typeof StatusSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/status-pages': {
      id: '/app/status-pages'
      path: '/status-pages'
      fullPath: '/app/status-pages'
      preLoaderRoute: typeof AppStatusPagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitors': {
      id: '/app/monitors'
      path: '/monitors'
      fullPath: '/app/monitors'
      preLoaderRoute: typeof AppMonitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/incidents': {
      id: '/app/incidents'
      path: '/incidents'
      fullPath: '/app/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/components': {
      id: '/app/components'
      path: '/components'
      fullPath: '/app/components'
      preLoaderRoute: typeof AppComponentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhooks/$monitorId': {
      id: '/api/webhooks/$monitorId'
      path: '/api/webhooks/$monitorId'
      fullPath: '/api/webhooks/$monitorId'
      preLoaderRoute: typeof ApiWebhooksMonitorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppComponentsRoute: typeof AppComponentsRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppMonitorsRoute: typeof AppMonitorsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatusPagesRoute: typeof AppStatusPagesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppComponentsRoute: AppComponentsRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppMonitorsRoute: AppMonitorsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatusPagesRoute: AppStatusPagesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  StatusSlugRoute: StatusSlugRoute,
  ApiWebhooksMonitorIdRoute: ApiWebhooksMonitorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
